<?php

namespace AppBundle\Repository;

use AppBundle\Filter\ApplicableToListQuery;
use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getList(ApplicableToListQuery $filter)
    {
        $builder = $this->_em->createQueryBuilder();
        $builder->select('item')
            ->from('AppBundle:Item', 'item')
            ->orderBy('item.id', 'ASC');

        $filter->apply($builder);

        return $builder;
    }

    public function getStats(){
        $result = $this->getEntityManager()->createQueryBuilder()->
        select('x.category,count(x.id) as cnt')->
        from('AppBundle:Item','x')->
        groupBy('x.category')->
        getQuery()->getResult();
        return $result;
    }

}
